name: Gitleaks Scan and Clone

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual runs
  pull_request:  # Triggers on pull requests
  push:  # Triggers on push events

jobs:
  gitleaks_scan:
    runs-on: ubuntu-latest

    steps:
      # Clone the external test repository
      - name: Clone test repository
        run: |
          # Replace with the URL of the repo you want to scan
          git clone https://github.com/tmclough/test-files.git
          # Navigate into the cloned directory
          cd test-files

      # Run Gitleaks on the cloned repository
      - name: Run Gitleaks on the cloned repository
        uses: gitleaks/gitleaks-action@v2
        with:
          scan-type: "repo"  # Default scan type
          report-format: "json"  # Output format
          report-path: "gitleaks_report.json"  # Path to save the report
          source: "./test-files"  # Path to the cloned repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for pushing back to the repository
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}  # Only required for organizations (not personal repos)

      # Upload Gitleaks Report as Artifact
      - name: Upload Gitleaks Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks_report.json
